<?xml version="1.0" encoding="utf-8"?><Database Name="LocalDB" Class="LocalDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-NUM253S\SQLEXPRESS;Initial Catalog=LocalDB;Integrated Security=True" SettingsObjectName="DataModel.Properties.Settings" SettingsPropertyName="LocalDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Datos" Member="Datos">
    <Type Name="Datos">
      <Column Name="Nombres" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellidos" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Edad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cedula" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Puesto" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Sueldos_Datos" Member="Sueldos" ThisKey="Puesto" OtherKey="Id" Type="Sueldos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Parametros" Member="Parametros">
    <Type Name="Parametros">
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Valor" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sueldos" Member="Sueldos">
    <Type Name="Sueldos">
      <Column Name="Puesto" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Sueldo" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Sueldos_Datos" Member="Datos" ThisKey="Id" OtherKey="Puesto" Type="Datos" />
    </Type>
  </Table>
  <Function Name="dbo.IngresarDatos" Method="IngresarDatos">
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="apellidos" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="cedula" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="edad" Type="System.Int32" DbType="Int" />
    <Parameter Name="id" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="puesto" Type="System.Guid" DbType="UniqueIdentifier" />
    <Return Type="System.Int32" />
  </Function>
</Database>